apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e5kqi2bkw-java-springboot
  janus-idp.io/tekton: e5kqi2bkw-java-springboot
  backstage.io/kubernetes-id: e5kqi2bkw-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e5kqi2bkw-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
